[GearGame.GearLeaderboardSettings]
MapNamesToContextValues=(MapName=MP_Avalanche,ContextValue=1)
MapNamesToContextValues=(MapName=MP_BloodDrive,ContextValue=2)
MapNamesToContextValues=(MapName=MP_DayOne,ContextValue=3)
MapNamesToContextValues=(MapName=MP_Hail,ContextValue=4)
MapNamesToContextValues=(MapName=MP_Jacinto,ContextValue=5)
MapNamesToContextValues=(MapName=MP_Pavilion,ContextValue=6)
MapNamesToContextValues=(MapName=MP_River,ContextValue=7)
MapNamesToContextValues=(MapName=MP_Ruins,ContextValue=8)
MapNamesToContextValues=(MapName=MP_Security,ContextValue=9)
MapNamesToContextValues=(MapName=MP_Stasis,ContextValue=10)

;MapNamesToContextValues=(MapName=MP_Gridlock,ContextValue=11)
;MapNamesToContextValues=(MapName=MP_Canals,ContextValue=12)
;MapNamesToContextValues=(MapName=MP_Mansion,ContextValue=13)
;MapNamesToContextValues=(MapName=MP_Subway,ContextValue=14)
;MapNamesToContextValues=(MapName=MP_Trainstation,ContextValue=15)

;MapNamesToContextValues=(MapName=MP_Flood,ContextValue=16)
;MapNamesToContextValues=(MapName=MP_Goldrush,ContextValue=17)
;MapNamesToContextValues=(MapName=MP_Fuel,ContextValue=18)

;MapNamesToContextValues=(MapName=MP_Highway,ContextValue=19)
;MapNamesToContextValues=(MapName=MP_Sanctuary,ContextValue=20)
;MapNamesToContextValues=(MapName=MP_Waystation,ContextValue=21)

;MapNamesToContextValues=(MapName=MP_Courtyard,ContextValue=22)
;MapNamesToContextValues=(MapName=MP_Grindyard,ContextValue=23)
;MapNamesToContextValues=(MapName=MP_Underhill,ContextValue=24)



[Engine.OnlinePlaylistManager]
DatastoresToRefresh=GameResources
Playlists=(PlaylistId=1,Name="Any",TeamSize=5,TeamCount=2,ConfiguredGames=((GameSettingId=1,GameSettingsClassName="GearGame.GearWarzoneSettings"),(GameSettingId=2,GameSettingsClassName="GearGame.GearExecutionSettings"),(GameSettingId=3,GameSettingsClassName="GearGame.GearAnnexSettings"),(GameSettingId=4,GameSettingsClassName="GearGame.GearKothSettings"),(GameSettingId=5,GameSettingsClassName="GearGame.GearAssassinationSettings"),(GameSettingId=6,GameSettingsClassName="GearGame.GearMeatflagSettings")))
Playlists=(PlaylistId=2,Name="Elimination",TeamSize=5,TeamCount=2,ConfiguredGames=((GameSettingId=1,GameSettingsClassName="GearGame.GearWarzoneSettings"),(GameSettingId=2,GameSettingsClassName="GearGame.GearExecutionSettings"),(GameSettingId=5,GameSettingsClassName="GearGame.GearAssassinationSettings")))
Playlists=(PlaylistId=3,Name="Territories",TeamSize=5,TeamCount=2,ConfiguredGames=((GameSettingId=3,GameSettingsClassName="GearGame.GearAnnexSettings"),(GameSettingId=4,GameSettingsClassName="GearGame.GearKothSettings"),(GameSettingId=6,GameSettingsClassName="GearGame.GearMeatflagSettings")))
Playlists=(PlaylistId=5,Name="Horde",TeamSize=5,TeamCount=1,ConfiguredGames=((GameSettingId=8,GameSettingsClassName="GearGame.GearHordeSettings")))
Playlists=(PlaylistId=6,Name="Wingman",TeamSize=2,TeamCount=5,ConfiguredGames=((GameSettingId=7,GameSettingsClassName="GearGame.GearWingmanSettings")))
Playlists=(PlaylistId=7,Name="DLC",TeamSize=5,TeamCount=2,ContentIds=(1),ConfiguredGames=((GameSettingId=1,GameSettingsClassName="GearGame.GearWarzoneSettings"),(GameSettingId=2,GameSettingsClassName="GearGame.GearExecutionSettings"),(GameSettingId=3,GameSettingsClassName="GearGame.GearAnnexSettings"),(GameSettingId=4,GameSettingsClassName="GearGame.GearKothSettings"),(GameSettingId=5,GameSettingsClassName="GearGame.GearAssassinationSettings"),(GameSettingId=6,GameSettingsClassName="GearGame.GearMeatflagSettings")))


;============================================
; PlaylistGameType Data Providers
;============================================
[DefaultWarzone GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultWarzone
MPGameMode=eGEARMP_Warzone
GameTypeId=1

[DefaultExecution GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultExecution
MPGameMode=eGEARMP_Execution
GameTypeId=2

[DefaultAnnex GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultAnnex
MPGameMode=eGEARMP_Annex
GameTypeId=3

[DefaultKOTH GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultKOTH
MPGameMode=eGEARMP_KOTH
GameTypeId=4

[DefaultGuardian GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultGuardian
MPGameMode=eGEARMP_KTL
GameTypeId=5

[DefaultMeatflag GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultMeatflag
MPGameMode=eGEARMP_CTM
GameTypeId=6

[DefaultWingman GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultWingman
MPGameMode=eGEARMP_Wingman
GameTypeId=7

[DefaultHorde GearGamePlaylistGameTypeProvider]
PlaylistGameTypeName=DefaultHorde
MPGameMode=eGEARMP_CombatTrials
GameTypeId=8

;============================================
; Playlist Data Providers
;============================================
[DefaultAny OnlinePlaylistProvider]
PlaylistId=1
PlaylistGameTypeNames=DefaultWarzone
PlaylistGameTypeNames=DefaultExecution
PlaylistGameTypeNames=DefaultAnnex
PlaylistGameTypeNames=DefaultKOTH
PlaylistGameTypeNames=DefaultGuardian
PlaylistGameTypeNames=DefaultMeatflag

[DefaultElimination OnlinePlaylistProvider]
PlaylistId=2
PlaylistGameTypeNames=DefaultWarzone
PlaylistGameTypeNames=DefaultExecution
PlaylistGameTypeNames=DefaultGuardian

[DefaultTerritories OnlinePlaylistProvider]
PlaylistId=3
PlaylistGameTypeNames=DefaultAnnex
PlaylistGameTypeNames=DefaultKOTH
PlaylistGameTypeNames=DefaultMeatflag

[Horde OnlinePlaylistProvider]
PlaylistId=5
PlaylistGameTypeNames=DefaultHorde

[DefaultWingman OnlinePlaylistProvider]
PlaylistId=6
PlaylistGameTypeNames=DefaultWingman

[DefaultDLC OnlinePlaylistProvider]
PlaylistId=7
PlaylistGameTypeNames=DefaultWarzone
PlaylistGameTypeNames=DefaultExecution
PlaylistGameTypeNames=DefaultAnnex
PlaylistGameTypeNames=DefaultKOTH
PlaylistGameTypeNames=DefaultGuardian
PlaylistGameTypeNames=DefaultMeatflag


[Engine.Engine]
bSubtitles=True
Subtitles=True
bShowSubtitles=True
bSubtitleCutscenes=True
bSubtitleRadio=True
SubtitleFontScale=2.2
UIScaleMultiplier=1.8
bScaleSubtitles=True

[Engine.Subtitle]
bSubtitles=True
Subtitles=True
bShowSubtitles=True
bSubtitleCutscenes=True
bSubtitleRadio=True
SubtitleFontScale=2.2
UIScaleMultiplier=1.8
bScaleSubtitles=True

[GearGame.GearEngine]
bSubtitles=True
Subtitles=True
bShowSubtitles=True
bSubtitleCutscenes=True
bSubtitleRadio=True
SubtitleFontScale=2.2
UIScaleMultiplier=1.8
bScaleSubtitles=True
