[GearGame.GearAI]
MinDistBetweenMantles=1024
EnemyDistance_Melee=256.f
EnemyDistance_Short=650.f
EnemyDistance_Medium=1600.f
EnemyDistance_Long=3600.f
FriendlyDistance_Medium=1400.f
GrenAwarnessDistance=700.f
GrenAwarnessDelay=0.5f;
MinDamageReceivedTime=1.f
ChanceToCoverUnderFire=0.15f
ChanceToEvade=0.005f
ChanceToEvadeGrenade=0.45f
ChanceToBeSuprisedByFlank=1.00f
#only grenadiers and hunters toss grenades
GrenadeChanceScale=0.f  
GrenadeMartyrChance=0.75
InterpEnemyLocSpeed=0.15f

Response_MinEnemySeenTime=0.5f
Response_MinEnemyHearTime=0.25f
Response_MinEnemyHurtTime=0.25f
Response_EnemyTooLongNoSeeTime=20.f

ActiveReloadAttemptPct=0.25f
ActiveReloadSweetPct=0.0f
ActiveReloadJamPct=0.25f

StumbleDownFromCloseRangeShotDistance=1024.0f

# delay before AI recognizes DBNO pawns for execute/revive
ExecuteDelay=3.0
ReviveDelay=1.0

# accuracy modifiers below
# Base spread angle %

AI_Base_Acc_Standing=0.15
AI_Base_Acc_BlindFire=1.00
AI_Base_Acc_Target=0.0

# Added spread angle % (modifiers)
AI_mod_Acc_Move=0.1
AI_mod_Acc_TargMove=0.15
AI_mod_Acc_Evade=0.50
AI_mod_Acc_BriefAcquire=0.25
AI_mod_Acc_BriefVisibility=0.15
AI_mod_Acc_Shield=0.1
AI_modrng_Short=-0.15f
AI_modrng_Medium=-0.05f
AI_modrng_Long=-0.f

#debug 
bAILogging=TRUE
bAILogToWindow=FALSE
bFlushAILogEachLine=false
bDrawAIDebug=TRUE
bDrawAIDebug_Range=FALSE
bMapBasedLogName=true
AILogFilter=Enemy
AILogFilter=AcquireCover
AILogFilter=Accuracy
AILogFilter=Loop
AILogFilter=Weapon
AILogFilter=WeaponFiring
AILogFilter=Cover
AILogFilter=Damage
AILogFilter=RouteDebug

[GearGame.GearAI_Cover]
MinStayAtCoverTime=10.f
MeatShield_Reaction_MinTimeInterval=10.0f
MeatShield_Reaction_Chance=0.7f
MeatShield_Reaction_Delay=1.0f

[GearGame.GearAI_Theron]
ActiveReloadAttemptPct=0.5f
ActiveReloadSweetPct=0.25f
ActiveReloadJamPct=0.05f
; tweaked aiming modifiers so they're a little less deadly with the bow
AI_Base_Acc_Standing=0.20
AI_Base_Acc_Target=0.10

[GearGame.GearAI_LocustGrenadier]
GrenadeChanceScale=2.f
EnemyDistance_Short=850.f
EnemyDistance_Medium=1600.f

[GearGame.GearAI_Hunter]
GrenadeChanceScale=2.f

[GearGame.GearAI_HunterArmored]
GrenadeChanceScale=2.f




[GearGame.GearAI_COGGear]
DefaultTetherDist=768.f
ChanceToCoverUnderFire=0.25f
GrenadeChanceScale=2.5f
EnemyDistance_Short=1024.f
EnemyDistance_Medium=2048.f
bAILogToWindow=FALSE

[GearGame.GearAI_Dom]
bAILogToWindow=FALSE

[GearGame.GearAI_Carmine]
bAILogToWindow=FALSE

[GearGame.GearAI_Tai]
bAILogToWindow=FALSE

[GearGame.GearAI_Wretch]
CircleDistance=(X=128.f,Y=256.f)

[GearGame.GearAI_Boomer]
# accuracy modifiers below
# Base spread angle %
AI_Base_Acc_Standing=0.15
AI_Base_Acc_BlindFire=1.00
AI_Base_Acc_Target=0.1
# Added spread angle % (modifiers)
AI_mod_Acc_Move=0.16
AI_mod_Acc_TargMove=0.1
AI_mod_Acc_Evade=0.50
Response_EnemyTooLongNoSeeTime=10.f
bAILogToWindow=FALSE

[GearGame.GearAI_Boomer_Shield]
ShieldOpenGroundSpeed=75
bAILogToWindow=FALSE
EnemyDistance_Melee=200.f
EnemyDistance_Short=384.f
EnemyDistance_Medium=512.f
EnemyDistance_Long=800.f



[GearGame.GearAI_Berserker]
EnemyDistance_Melee=200.f
EnemyDistance_Short=384.f
EnemyDistance_Medium=512.f
EnemyDistance_Long=800.f
Response_MinEnemySeenTime=1.25f
Response_MinEnemyHearTime=0.1f
Response_MinEnemyHurtTime=0.25f
ChargeBreakCount=2
NumFootSteps=2
MaxSearchTime=15.f
SniffTime=(X=2.f,Y=3.f)

ChargeAdjustFOV=0.93

ChargeAdjustDist=448

NextHearTime=1.5f


[GearGame.GearAI_Nemacyst]
HearingRadius=4096.f
bAILogToWindow=FALSE

[GearGame.GearAI_Corpser]
EnemyDistance_Melee=950.f
EnemyDistance_Short=950.f
EnemyDistance_Medium=2000.f
EnemyDistance_Long=3100.f
WretchTurtleTime=10.f
InitialAttackDelay=5.f

[GearGame.GearAI_TDM]
bCanHeadshot=TRUE
MinStayAtCoverTime=5.0
GrenadeChanceScale=2.0
ActiveReloadAttemptPct=0.6f
ActiveReloadSweetPct=0.4f
ActiveReloadJamPct=0.15f
MeatShield_Reaction_Chance=0.0
ExecuteDelay=0.0
ReviveDelay=1.0
HammerburstChance=0.33
Response_EnemyTooLongNoSeeTime=60.0

[GearGame.GearAI_CTMVictim]
ExecuteDelay=2.0

[GearGame.GearAI_Reaver]
bAILogToWindow=FALSE

[GearGame.GearAI_ReaverGunner]

[GearGame.GearAI_Jack]
bAILogToWindow=FALSE


[GearGame.GearAI_Brumak]
NextSuperAttackTime=20.f
EnemyDistance_Melee=720.f
EnemyDistance_Short=1100.f
EnemyDistance_Medium=2400.f
EnemyDistance_Long=8000.f
AI_mod_Acc_Move=0.1
AI_mod_Acc_TargMove=0.1
AI_mod_Acc_Evade=0.50
AI_mod_Acc_BriefAcquire=0.1
AI_mod_Acc_BriefVisibility=0.1
AI_modrng_Short=-0.15f
AI_modrng_Medium=-0.05f
AI_modrng_Long=-0.f
bDrawAIDebug_Range=FALSE
bDrawAIDebug_Enemy=TRUE
bAILogToWindow=FALSE

[GearGame.GearAI_Brumak_Kadar]
NewDefaultHealth=13000

[GearGame.GearAI_Bloodmount]
EnemyDistance_Melee=350.f
bDrawAIDebug_Range=FALSE
bDrawAIDebug_Enemy=TRUE
MaxRoamDist=1024.f
RoamEnvelopeOuter=1900.0f
RoamEnvelopeInner=512.f
EnemyDistance_Short=850.f
RoamWaitMin=0.5f
RoamWaitMax=1.5f
OverallRoamDurationMax=12

[GearGame.AIReactCond_BloodMountHeadDamage]
HeadDamageThreshold=125

[GearGame.GearAI_Ticker]
ExplosionHealthThresh=100.f

[GearGame.GearAI_Kantus]
GrenadeChanceScale=0.18f ;was 32
MinTimeBetweenKnockDownScreams=2.0f
KnockdownRange=1056
KnockDownFOV=0.5
KnockdownDelay=0.5f
MaxRoamDist=1024
ChanceToEvade=0.3
DamageBeforeEvade=200
TickerHealthThreshold=200
NumTickersToSpawn=2
MinionSpawnDelay=1.5f
MinTimeBetweenMinionSpawns=10.0
ReviveDelay=0

[GearGame.GearAI_SecurityBotFlying]
CirclingRadius=300
CirclingPeriod=1
EnemyAcquiredGracePeriod=1.5

[GearGame.GearAI_Speedy]
MinStayAtCoverTime=1.0f
MinDistBetweenMantles=1500

[GearGame.GearAI_Sire]
ExecuteDelay=0.0

[GearGame.GearAI_Leviathan]
bAILogToWindow=FALSE



