[Configuration]
BasedOn=..\GearGame\Config\DefaultPawn.ini

[GearGame.GearPawn]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f
HealthRechargeDelay=3.f
MaxKnockdownTime=2.0
bShouldCheckShieldCheat=true
ChainsawInterruptThreshold=1
PostEvadeFireDelay=0.15
PostRoadieRunFireDelay=0.25

[GearGame.GSM_StumbleFromMelee]
SpeedModifier=1.5

[GearGame.GSM_StumbleFromMelee2]
SpeedModifier=1.5

[GearGame.GearPC]
bTutorialMode=false

[GearGame.GearPawn_Infantry]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f
HealthRechargeDelay=3.f
# player gets hit in head a lot, because often standing behind partial cover, so don't penalize that much for that
LocDmgArray=(fDamageMultiplier=1.25,BodyPartName="Head",BoneNameArray=("b_MF_Head","b_MF_Face","b_MF_Neck"))
LocDmgArray=(fDamageMultiplier=0.75,BodyPartName="LeftLeg",BoneNameArray=("b_MF_Thigh_L","b_MF_Calf_L","b_MF_Foot_L"))
LocDmgArray=(fDamageMultiplier=0.75,BodyPartName="RightLeg",BoneNameArray=("b_MF_Thigh_R","b_MF_Calf_R","b_MF_Foot_R"))

[GearGame.GearPawn_COGGear]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=15.f
HealthRechargeDelay=3.f

[GearGameContent.GearPawn_LocustMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_LocustSniperMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_LocustTheronMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f
LocDmgArray=(fDamageMultiplier=0.0f,BodyPartName="FlappyBits",BoneNameArray=("BackCloak", "BackCloak_Lt01", "BackCloak_Lt02", "BackCloak_Rt01", "BackCloak_Rt02", "Front_Cloak", "FrontCloak_Lt01", "FrontCloak_Lt02", "FrontCloak_Rt01", "FrontCloak_Rt02"))


[GearGameContent.GearPawn_LocustTheronWithHelmetMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f
LocDmgArray=(fDamageMultiplier=0.0f,BodyPartName="FlappyBits",BoneNameArray=("BackCloak", "BackCloak_Lt01", "BackCloak_Lt02", "BackCloak_Rt01", "BackCloak_Rt02", "Front_Cloak", "FrontCloak_Lt01", "FrontCloak_Lt02", "FrontCloak_Rt01", "FrontCloak_Rt02"))


[GearGameContent.GearPawn_LocustGeneralRaamMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f
LocDmgArray=(fDamageMultiplier=0.0f,BodyPartName="FlappyBits",BoneNameArray=("BackCloak", "BackCloak_Lt01", "BackCloak_Lt02", "BackCloak_Rt01", "BackCloak_Rt02", "Front_Cloak", "FrontCloak_Lt01", "FrontCloak_Lt02", "FrontCloak_Rt01", "FrontCloak_Rt02"))


[GearGameContent.GearPawn_LocustHunterArmorMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_LocustHunterNoArmorMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f



[GearGameContent.GearPawn_LocustBoomer]
DefaultHealth=2000
DefaultGroundSpeed=200
HealthRechargePercentPerSecond=15.f


[GearGame.GearPawn_LocustWretchBase]
DefaultGroundSpeed=1000
DefaultHealth=250

[GearGameContent.GearPawn_LocustDarkWretch]
DefaultGroundSpeed=1250
DefaultHealth=375



[GearGameContent.GearPawn_COGMarcusMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_COGDomMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_COGBairdMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_COGDizzyMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_COGTaiMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_COGGusMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_COGMinhMP]
DefaultHealth=600
HealthRechargePercentPerSecond=25.f


[GearGameContent.GearPawn_COGHoffmanMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_COGCarmineMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustSkorgeMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustFlameDroneMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustKantusMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustTheronMPBase]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustHunterBaseMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustChopperMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustDroneMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f

[GearGameContent.GearPawn_LocustBaseMP]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f
bCanRoadieRun=TRUE
bCanSwatTurn=TRUE

[GearGameContent.GearPawn_StrandedMP]
DefaultHealth=600
DefaultGroundSpeed=275

[GearGameContent.GearPawn_MeatflagBase]
DefaultHealth=600
DefaultGroundSpeed=300
HealthRechargePercentPerSecond=25.f



