[GearGame.GearCameraMode_Cover]
bSmerp=False
MinOffset=(X=0.000000,Y=100.000000,Z=0.000000)
MidOffset=(X=-100.000000,Y=0.000000,Z=0.000000)
MaxOffset=(X=0.000000,Y=-100.000000,Z=0.000000)
CrouchMinOffset=(X=-60.000000,Y=100.000000,Z=0.000000)
CrouchMidOffset=(X=-60.000000,Y=0.000000,Z=0.000000)
CrouchMaxOffset=(X=-60.000000,Y=-100.000000,Z=0.000000)
LeanMinOffset=(X=-100.000000,Y=100.000000,Z=-10.000000)
LeanMidOffset=(X=-14.000000,Y=15.000000,Z=0.000000)
LeanMaxOffset=(X=30.000000,Y=-70.000000,Z=5.000000)
CrouchLeanMinOffset=(X=-64.000000,Y=100.000000,Z=-30.000000)
CrouchLeanMidOffset=(X=-14.000000,Y=15.000000,Z=-25.000000)
CrouchLeanMaxOffset=(X=30.000000,Y=-70.000000,Z=-20.000000)
LeanMinRoll=1920
LeanMaxRoll=0
CrouchLeanMinRoll=1920
CrouchLeanMaxRoll=0
BaseRotationOffset=(Pitch=0,Yaw=0,Roll=0)
UpperLimit=(Pitch=0,Yaw=16384,Roll=0)
LowerLimit=(Pitch=0,Yaw=-16384,Roll=0)
LeanUpperLimit=(Pitch=0,Yaw=16384,Roll=0)
LeanLowerLimit=(Pitch=0,Yaw=-2048,Roll=0)
AlphaInTime=0.500000
AlphaOutTime=0.500000

[GearGame.GearCamMod_CameraBone]
#to re-enable camera anims for tweaking or whatnot, set this to false
bOXMShakyCamDampening=true
OXMShakyCamDampeningFactor=0.15f
RoadieRunShakyCamDampeningFactor=0.4f
AlphaWhenIdle=0.3
InCombatAlphaBonus=0.1

[GearGame.GearGameplayCameraMode]
FOVAngle=70

[GearGame.GameplayCam_Cover]
FOVAngle=95

[GearGame.GameplayCam_CoverTargeting]
#equipped weapon can override this
FOVAngle=50

[GearGame.GameplayCam_CoverTargetingGrenade]
#equipped weapon can override this
FOVAngle=70

[GearGame.GameplayCam_DBNO]
FOVAngle=80

[GearGame.GameplayCam_Death]
FOVAngle=80

[GearGame.GameplayCam_Jack]
FOVAngle=90

[GearGame.GameplayCam_RoadieRun]
FOVAngle=105

[GearGame.GameplayCam_Targeting]
FOVAngle=50

[GearGame.GameplayCam_TargetingGrenade]
#equipped weapon can override this
FOVAngle=70

[GearGame.GearCameraMode]
FOVAngle=80

[GearGame.GameplayCam_Default]
FOVAngle=110

[GearGame.GameplayCam_VehicleTurret]
FOVAngle=90

[GearGame.GameplayCam_VehicleTurretTargeting]
FOVAngle=70

[GearGame.GameplayCam_BrumakDriver]
FOVAngle=100

[GearGame.GameplayCam_BrumakTargeting]
FOVAngle=60

[GearGame.GameplayCam_DeployedShield]
FOVAngle=80

[Engine.Engine]
bSubtitles=True
Subtitles=True
bShowSubtitles=True
bSubtitleCutscenes=True
bSubtitleRadio=True
SubtitleFontScale=2.2
UIScaleMultiplier=1.8
bScaleSubtitles=True

[Engine.Subtitle]
bSubtitles=True
Subtitles=True
bShowSubtitles=True
bSubtitleCutscenes=True
bSubtitleRadio=True
SubtitleFontScale=2.2
UIScaleMultiplier=1.8
bScaleSubtitles=True

[GearGame.GearEngine]
bSubtitles=True
Subtitles=True
bShowSubtitles=True
bSubtitleCutscenes=True
bSubtitleRadio=True
SubtitleFontScale=2.2
UIScaleMultiplier=1.8
bScaleSubtitles=True
